#------------------------------DATABASE-----------------------------#
#--------------------------START DATABASE---------------------------#
[Database_info]
DATABASE = "sqlite"
#-------------------------------sqlite------------------------------#
[db_type_1]
PATH = ".panoptes.db"
NOHOSTNAME =''
#-------------------------pymssql or pyodbc-------------------------#
[db_type_2]
USERNAME=""
PASSWORD=""
MYDATABASE=""
#---------------postgresql or psycopg2 or pg8000 or mysql-----------#
#--------------mysqlclient or PyMySQL or oracle or pymssql----------#
[db_type_3]
USERNAME=""
PASSWORD=""
PORT=""
HOSTNAME=""
MYDATABASE=""
#---------------------------END DATABASE----------------------------#
#####################################################################
#-------------------------------EXTRA-------------------------------#
[Extra]
EXTRA1 = "?check_same_thread=false"
#-----------------------------END EXTRA-----------------------------#

#####################################################################
#------------------Engine Configuration Parameters------------------#
#                                                                   #
#--------------------------START Parameters-------------------------#
[Parameters]                                                      
convert_unicode = true
#--------------------------END Parameters---------------------------#